export {default as defaultImg} from './default.svg';
export {default as headerLogo} from './headerLogo.svg';
export {default as sale} from './dashboard/sale.webp';
export {default as offer} from './dashboard/offer.png';
export {default as smart} from './dashboard/smart.webp';
export {default as pdOne} from './dashboard/pd1.jpg';
export {default as asu} from './dashboard/asu.webp';
export {default as dashThree} from './dashboard/dashThree.webp';
export {default as dashFour} from './dashboard/dashFour.webp';
export {default as dashFive} from './dashboard/dashFive.webp';
export {default as dashSix} from './dashboard/dashSix.webp';
export {default as offerImg}from "./product/OfferImg.jpg";
export {default as prd}from "./product/prd.jpg";
export {default as purple}from "./product/purple.jpg";
export {default as blue}from "./product/blue.jpg";
export {default as white}from "./product/white.jpg";
export {default as LGAC}from "./dashboard/LGAC.jpg";
export {default as fun}from "./dashboard/fun.png";
export {default as smwc}from "./dashboard/smwc.webp";
export {default as cam}from "./dashboard/cam.png";
export {default as tv}from "./dashboard/tv.jpeg";
export {default as pb}from "./dashboard/pb.jpg";
export {default as lap}from "./dashboard/lap.jpg";
export {default as trm}from "./dashboard/trm.jpg";
export {default as bn1}from "./dashboard/bn1.jpg";
export {default as bn2}from "./dashboard/bn2.jpg";
export {default as bn3}from "./dashboard/bn3.jpg";
export {default as bn4}from "./dashboard/bn4.jpg";
export {default as Rating   }from "./product/Rating.png";
